### ISSUE TITLE
Error PaperMC 1.20.6 Build #137

### ISSUE THREAD

**Issue by Cyberillc** [CPJiNan/AkariBan#3]
[20:52:53] [Server thread/INFO]: [AkariBan] Loading server plugin AkariBan v3.1.1
[20:52:53] [Server thread/INFO]: Loading AkariBan... 3.1.1
[20:52:54] [Server thread/WARN]: com.github.cpjinan.plugin.akariban.taboolib.common.inject.ClassVisitException: class com.github.cpjinan.plugin.akariban.taboolib.module.nms.MinecraftVersion#init: VisitorGroup{priority=0, list=[AwakeFunction(lifeCycle=NONE), AwakeFunction(lifeCycle=CONST), AwakeFunction(lifeCycle=INIT), AwakeFunction(lifeCycle=LOAD), AwakeFunction(lifeCycle=ENABLE), AwakeFunction(lifeCycle=ACTIVE), AwakeFunction(lifeCycle=DISABLE), com.github.cpjinan.plugin.akariban.taboolib.module.kether.KetherLoader@4b61d8b1, com.github.cpjinan.plugin.akariban.taboolib.platform.compat.PlaceholderExpansion$PlaceholderRegister@36a4fe62, com.github.cpjinan.plugin.akariban.taboolib.common.platform.command.SimpleCommandRegister@6e69900f]} (LOAD)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:144)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:112)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:75)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:42)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.common.TabooLib$1.run(TabooLib.java:79)
[20:52:54] [Server thread/WARN]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56)
[20:52:54] [Server thread/WARN]: 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:73)
[20:52:54] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[20:52:54] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[20:52:54] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[20:52:54] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[20:52:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510)
[20:52:54] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286)
[20:52:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
[20:52:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[20:52:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[20:52:54] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Unsupported Minecraft version, plugin disabled
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.module.nms.MinecraftVersion.init(MinecraftVersion.kt:206)
[20:52:54] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)
[20:52:54] [Server thread/WARN]: 	at AkariBan-3.1.1.jar//com.github.cpjinan.plugin.akariban.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:142)
[20:52:54] [Server thread/WARN]: 	... 18 more

**Comment by CPJiNan** [comment]
Taboolib 6.1 framework seems to not work on 1.20.6 , please follow for further updates.

**Comment by CPJiNan** [comment]
@Cyberillc Hi!

It looks like the Taboolib framework version 6.1.2-test1 may have added support for 1.20.6.
AkariBan has been upgraded to this version. Please try the latest build.

**Comment by CPJiNan** [comment]
Hi, @Cyberillc 

It looks like the Taboolib framework version 6.1.2-test1 may have added support for 1.20.6.
AkariBan has been upgraded to this version. Please try [the latest build](https://www.spigotmc.org/resources/117132/).

**Comment by CPJiNan** [comment]
After testing, it seems that the 3.0.7 version already supports 1.20.6 and 1.21.
